In [ ]:
import openmdao.api as om
import numpy as np
import pycycle.api as pyc

from pycycle.thermo.thermo import Thermo
from pycycle.thermo.cea.species_data import Properties

composition = {'H': 2.0, 'O': 1}

thermo_data = pyc.species_data.janaf
thermo_data
props = Properties(thermo_data, init_elements=composition)
#b0 = props.b0

p = om.Problem()
ivc = p.model.add_subsystem('ivc', om.IndepVarComp(), promotes=['*'])
ivc.add_output('T', val= 1073.0, units='degK')
ivc.add_output('P', val = 1.0, units='bar')
ivc.add_output('composition', val = props.b0)

thermo = Thermo(mode='total_TP', method='CEA', fl_name='Fl_O:tot', thermo_kwargs={'spec':thermo_data, 'composition': composition})

p.model.add_subsystem('thermo', thermo, promotes=['T', 'P', 'composition'])

p.setup(force_alloc_complex=True)
p.run_model()

p

+  
+  ==========================
+  thermo.base_thermo.chem_eq
+  ==========================
+  NL: Newton 0 ; 0.0877435688 1
+  NL: Newton 1 ; 0.67566751 7.70047901
+  NL: Newton 2 ; 1.5988425 18.2217628
+  NL: Newton 3 ; 3.44115543e-05 0.000392183208
+  NL: Newton 4 ; 2.07488728e-08 2.36471722e-07
+  NL: Newton Converged
|  LS: AG 1 ; 0.000219947367 1
|  +  
|  +  ==========================
|  +  thermo.base_thermo.chem_eq
|  +  ==========================
|  +  NL: Newton 0 ; 2.32639071e-08 1
|  +  NL: Newton Converged
|  LS: AG 2 ; 2.32639071e-08 0.5
+  
+  ==========================
+  thermo.base_thermo.chem_eq
+  ==========================
+  NL: Newton 0 ; 2.32639071e-08 1
+  NL: Newton Converged
|  LS: AG 1 ; 5.34917549e-05 1
|  +  
|  +  ==========================
|  +  thermo.base_thermo.chem_eq
|  +  ==========================
|  +  NL: Newton 0 ; 1.50571517e-08 1
|  +  NL: Newton Converged
|  LS: AG 2 ; 1.50571517e-08 0.5
+  
+  ==========================
+  thermo.base_th

In [ ]:
import openmdao.api as om
import numpy as np
import pycycle.api as pyc

from pycycle.thermo.thermo import Thermo
from pycycle.thermo.cea.species_data import Properties

In [ ]:
composition = {'H': 2.0, 'O': 1}

thermo_data = pyc.species_data.janaf

props = Properties(thermo_data, init_elements=composition)
#b0 = props.b0

In [ ]:
p['T']



array([1073.])

In [ ]:
p['composition']

array([0.11101687, 0.05550844])

In [ ]:
p.thermo

AttributeError: 'Problem' object has no attribute 'thermo'

In [ ]:
p['thermo.n_moles']

KeyError: "<model> <class Group>: Variable 'thermo.n_moles' not found. Perhaps you meant one of the following variables: ['thermo.R', 'thermo.S', 'thermo.base_thermo.n_moles', 'thermo.h', 'thermo.rho']."

In [ ]:
p = om.Problem()
ivc = p.model.add_subsystem('ivc', om.IndepVarComp(), promotes=['*'])
ivc.add_output('T', val= 1073.0, units='degK')
ivc.add_output('P', val = 1.0, units='bar')
ivc.add_output('composition', val = props.b0)

thermo = Thermo(mode='total_TP', method='CEA', fl_name='Fl_O:tot', thermo_kwargs={'spec':thermo_data, 'composition': composition})

p.model.add_subsystem('thermo', thermo, promotes=['T', 'P', 'composition'])

p.setup(force_alloc_complex=True)
p.run_model()

p

+  
+  ==========================
+  thermo.base_thermo.chem_eq
+  ==========================
+  NL: Newton 0 ; 0.0877435688 1
+  NL: Newton 1 ; 0.67566751 7.70047901
+  NL: Newton 2 ; 1.5988425 18.2217628
+  NL: Newton 3 ; 3.44115543e-05 0.000392183208
+  NL: Newton 4 ; 2.07488728e-08 2.36471722e-07
+  NL: Newton Converged
|  LS: AG 1 ; 0.000219947367 1
|  +  
|  +  ==========================
|  +  thermo.base_thermo.chem_eq
|  +  ==========================
|  +  NL: Newton 0 ; 2.32639071e-08 1
|  +  NL: Newton Converged
|  LS: AG 2 ; 2.32639071e-08 0.5
+  
+  ==========================
+  thermo.base_thermo.chem_eq
+  ==========================
+  NL: Newton 0 ; 2.32639071e-08 1
+  NL: Newton Converged
|  LS: AG 1 ; 5.34917549e-05 1
|  +  
|  +  ==========================
|  +  thermo.base_thermo.chem_eq
|  +  ==========================
|  +  NL: Newton 0 ; 1.50571517e-08 1
|  +  NL: Newton Converged
|  LS: AG 2 ; 1.50571517e-08 0.5
+  
+  ==========================
+  thermo.base_th

In [ ]:
p['thermo']

KeyError: "<model> <class Group>: Variable 'thermo' not found. Perhaps you meant one of the following variables: ['thermo.Cp', 'thermo.Cv', 'thermo.R', 'thermo.S', 'thermo.h']."

In [ ]:
p.thermo

AttributeError: 'Problem' object has no attribute 'thermo'

In [ ]:
p.thermo_data

AttributeError: 'Problem' object has no attribute 'thermo_data'

In [ ]:
p.thermo

AttributeError: 'Problem' object has no attribute 'thermo'

In [ ]:
p['thermo']

KeyError: "<model> <class Group>: Variable 'thermo' not found. Perhaps you meant one of the following variables: ['thermo.Cp', 'thermo.Cv', 'thermo.R', 'thermo.S', 'thermo.h']."

In [ ]:
p['thermo.n_moles']

KeyError: "<model> <class Group>: Variable 'thermo.n_moles' not found. Perhaps you meant one of the following variables: ['thermo.R', 'thermo.S', 'thermo.base_thermo.n_moles', 'thermo.h', 'thermo.rho']."

In [ ]:
p['thermo.composition']


KeyError: "<model> <class Group>: Variable 'thermo.composition' not found. Perhaps you meant one of the following variables: ['composition', 'thermo.Cp', 'thermo.Fl_O:tot:composition', 'thermo.base_thermo.n', 'thermo.h', 'thermo.rho']."

In [ ]:
p['thermo.base_thermo.n']


array([1.00000000e-10, 1.00000000e-10, 5.40818649e-08, 5.55083793e-02,
       1.00000000e-10, 1.00000000e-10, 2.96506194e-09, 2.61496670e-08])

In [ ]:
p['thermo.base_thermo.n_moles']


array([0.05550846])

In [ ]:
print(p.model.thermo.base_thermo.chem_eq.thermo.products)

AttributeError: 'ChemEq' object has no attribute 'thermo'

In [ ]:
print(p.model.thermo.base_thermo.thermo.products)

['H', 'HO2', 'H2', 'H2O', 'H2O2', 'O', 'OH', 'O2']


In [ ]:
sum(p['thermo.base_thermo.n'])

np.float64(0.05550846289398993)

In [ ]:
1/ sum(p['thermo.base_thermo.n'])

np.float64(18.01527096705596)

In [ ]:
n_sum = sum(p['thermo.base_thermo.n'])

In [ ]:
mole_species = p['thermo.base_thermo.n']

In [ ]:
mole_species

array([1.00000000e-10, 1.00000000e-10, 5.40818649e-08, 5.55083793e-02,
       1.00000000e-10, 1.00000000e-10, 2.96506194e-09, 2.61496670e-08])

In [ ]:
mole_species[3]/n_sum

np.float64(0.9999984939847099)

In [ ]:
mole_species[0]/n_sum

np.float64(1.8015270967055962e-09)

In [ ]:
mole_species[2]/n_sum

np.float64(9.742994511152381e-07)

In [ ]:
 #              H_atoms = 2 * 0.8 + 2 * 0.1 = 1.8
 #              O_atoms = 2 * 0.1 + 1 * 0.1 = 0.3
composition = {'H': 1.8, 'O': 0.3}

thermo_data = pyc.species_data.janaf

props = Properties(thermo_data, init_elements=composition)
#b0 = props.b0

In [ ]:
p = om.Problem()
ivc = p.model.add_subsystem('ivc', om.IndepVarComp(), promotes=['*'])
ivc.add_output('T', val= 1073.0, units='degK')
ivc.add_output('P', val = 1.0, units='bar')
ivc.add_output('composition', val = props.b0)

thermo = Thermo(mode='total_TP', method='CEA', fl_name='Fl_O:tot', thermo_kwargs={'spec':thermo_data, 'composition': composition})

p.model.add_subsystem('thermo', thermo, promotes=['T', 'P', 'composition'])

p.setup(force_alloc_complex=True)
p.run_model()

p

+  
+  ==========================
+  thermo.base_thermo.chem_eq
+  ==========================
+  NL: Newton 0 ; 0.185589463 1
+  NL: Newton 1 ; 0.625416649 3.36989309
+  NL: Newton 2 ; 1.77484595 9.56329052
+  NL: Newton 3 ; 0.101422604 0.546489024
+  NL: Newton 4 ; 1307.53537 7045.31038
+  NL: Newton 5 ; 0.00232776883 0.01254257
+  NL: Newton 6 ; 2.10435662e-08 1.13387721e-07
+  NL: Newton Converged
+  
+  ==========================
+  thermo.base_thermo.chem_eq
+  ==========================
+  NL: Newton 0 ; 3.36265871e-10 1
+  NL: Newton Converged
+  
+  ==========================
+  thermo.base_thermo.chem_eq
+  ==========================
+  NL: Newton 0 ; 1.04215364e-10 1
+  NL: Newton Converged
+  
+  ==========================
+  thermo.base_thermo.chem_eq
+  ==========================
+  NL: Newton 0 ; 5.87234717e-12 1
+  NL: Newton Converged


In [ ]:
mole_species

array([1.55920128e-09, 1.00000000e-10, 9.07151253e-02, 4.53575619e-02,
       1.00000000e-10, 1.00000000e-10, 1.00000000e-10, 1.00000000e-10])

In [ ]:
mole_species[3]/n_sum

np.float64(0.3333333248094561)

In [ ]:
mole_species[2]/n_sum

np.float64(0.666666660057446)

In [ ]:
mole_species[1]/n_sum

np.float64(7.349013275026305e-10)

In [ ]:
print(p.model.thermo.base_thermo.products)

AttributeError: 'SetTotalTP' object has no attribute 'products'

In [ ]:
print(p.model.thermo.base_thermo.thermo.products)

['H', 'HO2', 'H2', 'H2O', 'H2O2', 'O', 'OH', 'O2']


In [ ]:
mole_species[2]/n_sum

np.float64(0.666666660057446)

In [ ]:
mole_species[3]/n_sum

np.float64(0.3333333248094561)

In [ ]:
mole_species[4]/n_sum

np.float64(7.349013275026264e-10)

In [ ]:
mole_species[5]/n_sum

np.float64(7.349013275026264e-10)

In [ ]:
mole_species

array([1.55920128e-09, 1.00000000e-10, 9.07151253e-02, 4.53575619e-02,
       1.00000000e-10, 1.00000000e-10, 1.00000000e-10, 1.00000000e-10])

In [ ]:
mole_species[7]

np.float64(1.0000000000003966e-10)

In [ ]:
mole_species[3]

np.float64(0.04535756193858078)

In [ ]:


print(p.model.thermo.base_thermo.thermo.products)


['H', 'HO2', 'H2', 'H2O', 'H2O2', 'O', 'OH', 'O2']


In [ ]:
mole_species[6]

np.float64(1.0000000000000008e-10)

In [ ]:
mole_species[2]

np.float64(0.09071512529756093)

In [ ]:
mole_species[1]

np.float64(1.0000000000000057e-10)

In [ ]:
mole_species[3]

np.float64(0.04535756193858078)

In [ ]:
mole_species[2]/n_sum

np.float64(0.666666660057446)

In [ ]:
mole_species[3]/n_sum

np.float64(0.3333333248094561)

In [ ]:
print(p.model.thermo.base_thermo.properties)

AttributeError: 'SetTotalTP' object has no attribute 'properties'

In [ ]:
print(p.model.thermo.properties)

AttributeError: 'Thermo' object has no attribute 'properties'

In [ ]:
print(p.model.thermo)

In [ ]:
print(p.model.thermo.H)

AttributeError: 'Thermo' object has no attribute 'H'

In [ ]:
print(p.model.thermo.base_thermo.H)

AttributeError: 'SetTotalTP' object has no attribute 'H'

In [ ]:
print(p.model.thermo.base_thermo.thermo.H)

AttributeError: 'Properties' object has no attribute 'H'

In [ ]:
print(p.model.thermo.base_thermo.thermo.elements)

['H', 'O']


In [ ]:
print(p.model.thermo.base_thermo.thermo.products)

['H', 'HO2', 'H2', 'H2O', 'H2O2', 'O', 'OH', 'O2']


In [ ]:
print(p.model.thermo.base_thermo.thermo.b0)

[0.27214538 0.04535756]


In [ ]:
print(p.model.thermo.base_thermo.thermo.a)

[[ 6.07877425e+01 -1.81935442e-01  2.50021182e+00 -1.22651286e-07
   3.73287633e-11 -5.68774456e-15  3.41021020e-19  2.54748640e+04
  -4.48191777e-01  0.00000000e+00]
 [-1.81066972e+06  4.96319203e+03 -1.03949899e+00  4.56014853e-03
  -1.06185945e-06  1.14456788e-10 -4.76306416e-15 -3.19441874e+04
   4.06685092e+01  0.00000000e+00]
 [ 5.60812338e+05 -8.37149134e+02  2.97536304e+00  1.25224993e-03
  -3.74071842e-07  5.93662825e-11 -3.60699573e-15  5.33981585e+03
  -2.20276405e+00  0.00000000e+00]
 [ 1.03497210e+06 -2.41269856e+03  4.64611078e+00  2.29199831e-03
  -6.83683048e-07  9.42646893e-11 -4.82238053e-15 -1.38428651e+04
  -7.97814851e+00  0.00000000e+00]
 [ 1.48942803e+06 -5.17082178e+03  1.12820497e+01 -8.04239779e-05
  -1.81838377e-08  6.94726559e-12 -4.82783190e-16  1.41825104e+04
  -4.65085566e+01  0.00000000e+00]
 [ 2.61902026e+05 -7.29872203e+02  3.31717727e+00 -4.28133436e-04
   1.03610459e-07 -9.43830433e-12  2.72503830e-16  3.39242806e+04
  -6.67958535e-01  0.00000000e+00

In [ ]:
print(p.model.thermo.base_thermo.props.tp2props.h)

AttributeError: 'PropsCalcs' object has no attribute 'h'

In [ ]:
print(p.model.thermo.base_thermo.h)

AttributeError: 'SetTotalTP' object has no attribute 'h'

In [ ]:
print(p.model.thermo.h)

AttributeError: 'Thermo' object has no attribute 'h'

In [ ]:
print(p.model.thermo.base_thermo.props.tp2props.h)

AttributeError: 'PropsCalcs' object has no attribute 'h'

In [ ]:
np.zeros((5, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
in_elem = ['H']

In [ ]:
out_elem = ['H', 'O']

In [ ]:
n_in = len((in_elem, out_elem))

In [ ]:
n_in = len((in_elem))

In [ ]:
n_out = len(out_elem)

In [ ]:
_in_elem = ['H']

In [ ]:
_out_elem = ['H', 'O']

In [ ]:
_map = np.zeros((n_out, n_in))
for i, elem in enumerate(_in_elem):
    if elem in _out_elem:
        j = _out_elem.index(elem)
        _map[j, i] = 1.0



In [ ]:
_map

array([[1.],
       [0.]])

In [ ]:
_O_out_idx = (_out_elem.index('O')
                           if 'O' in _out_elem else None)



In [ ]:
_O_out_idx

1

In [ ]:
print(_O_out_idx)

1


In [ ]:
p['thermo.Fl_I:tot:composition']

KeyError: "<model> <class Group>: Variable 'thermo.Fl_I:tot:composition' not found. Perhaps you meant one of the following variables: ['thermo.Fl_O:tot:Cp', 'thermo.Fl_O:tot:Cv', 'thermo.Fl_O:tot:P', 'thermo.Fl_O:tot:R', 'thermo.Fl_O:tot:S', 'thermo.Fl_O:tot:T', 'thermo.Fl_O:tot:composition', 'thermo.Fl_O:tot:gamma', 'thermo.Fl_O:tot:h', 'thermo.Fl_O:tot:rho']."

In [ ]:
p['thermo.Fl_O:tot:composition']

array([0.27214538, 0.04535756])

In [ ]:
1/ p['thermo.Fl_O:tot:composition'][0]

np.float64(3.674506666666666)

In [ ]:
1/ p['thermo.Fl_O:tot:composition'][1]

np.float64(22.04704)

In [ ]:
p['thermo.base_thermo.n']

array([1.55920128e-09, 1.00000000e-10, 9.07151253e-02, 4.53575619e-02,
       1.00000000e-10, 1.00000000e-10, 1.00000000e-10, 1.00000000e-10])

In [ ]:
print(p.model.thermo.base_thermo.thermo.elements)

['H', 'O']


In [ ]:
p['thermo.Fl_I:tot:composition']

KeyError: "<model> <class Group>: Variable 'thermo.Fl_I:tot:composition' not found. Perhaps you meant one of the following variables: ['thermo.Fl_O:tot:Cp', 'thermo.Fl_O:tot:Cv', 'thermo.Fl_O:tot:P', 'thermo.Fl_O:tot:R', 'thermo.Fl_O:tot:S', 'thermo.Fl_O:tot:T', 'thermo.Fl_O:tot:composition', 'thermo.Fl_O:tot:gamma', 'thermo.Fl_O:tot:h', 'thermo.Fl_O:tot:rho']."

In [ ]:
p['thermo.Fl_O:tot:composition']

array([0.27214538, 0.04535756])

In [ ]:
p['thermo.base_thermo.thermo.elements']

KeyError: "<model> <class Group>: Variable 'thermo.base_thermo.thermo.elements' not found. Perhaps you meant one of the following variables: ['thermo.base_thermo.ls2p.A', 'thermo.base_thermo.ls2p.b', 'thermo.base_thermo.ls2p.x', 'thermo.base_thermo.ls2t.A', 'thermo.base_thermo.ls2t.b', 'thermo.base_thermo.ls2t.x', 'thermo.base_thermo.n', 'thermo.base_thermo.n_moles']."

In [ ]:
p['thermo.Fl_I:tot:composition']

KeyError: "<model> <class Group>: Variable 'thermo.Fl_I:tot:composition' not found. Perhaps you meant one of the following variables: ['thermo.Fl_O:tot:Cp', 'thermo.Fl_O:tot:Cv', 'thermo.Fl_O:tot:P', 'thermo.Fl_O:tot:R', 'thermo.Fl_O:tot:S', 'thermo.Fl_O:tot:T', 'thermo.Fl_O:tot:composition', 'thermo.Fl_O:tot:gamma', 'thermo.Fl_O:tot:h', 'thermo.Fl_O:tot:rho']."

In [ ]:
p['thermo.Fl_O:tot:composition']

array([0.27214538, 0.04535756])

In [ ]:
p['thermo.base_thermo.thermo.elements']

KeyError: "<model> <class Group>: Variable 'thermo.base_thermo.thermo.elements' not found. Perhaps you meant one of the following variables: ['thermo.base_thermo.ls2p.A', 'thermo.base_thermo.ls2p.b', 'thermo.base_thermo.ls2p.x', 'thermo.base_thermo.ls2t.A', 'thermo.base_thermo.ls2t.b', 'thermo.base_thermo.ls2t.x', 'thermo.base_thermo.n', 'thermo.base_thermo.n_moles']."

In [ ]:
1 / sum(p['thermo.Fl_I:tot:composition'])

KeyError: "<model> <class Group>: Variable 'thermo.Fl_I:tot:composition' not found. Perhaps you meant one of the following variables: ['thermo.Fl_O:tot:Cp', 'thermo.Fl_O:tot:Cv', 'thermo.Fl_O:tot:P', 'thermo.Fl_O:tot:R', 'thermo.Fl_O:tot:S', 'thermo.Fl_O:tot:T', 'thermo.Fl_O:tot:composition', 'thermo.Fl_O:tot:gamma', 'thermo.Fl_O:tot:h', 'thermo.Fl_O:tot:rho']."

In [ ]:
1 / sum(p['thermo.Fl_O:tot:composition'])

np.float64(3.1495771428571424)

In [ ]:
sum(p['thermo.Fl_O:tot:composition'])

np.float64(0.3175029391700655)

In [ ]:
1/ sum(p['thermo.base_thermo.n'])

np.float64(7.349013275026263)

In [ ]:
 #              H_atoms = 2 * 0.8 + 2 * 0.1 = 1.8
 #              O_atoms = 2 * 0.1 + 1 * 0.1 = 0.3
composition = {'H': 1.8, 'O': 0.3}

thermo_data = pyc.species_data.janaf

props = Properties(thermo_data, init_elements=composition)
#b0 = props.b0

In [ ]:
p = om.Problem()
ivc = p.model.add_subsystem('ivc', om.IndepVarComp(), promotes=['*'])
ivc.add_output('T', val= 1073.0, units='degK')
ivc.add_output('P', val = 1.0, units='bar')
ivc.add_output('composition', val = props.b0)

thermo = Thermo(mode='total_TP', method='CEA', fl_name='Fl_O:tot', thermo_kwargs={'spec':thermo_data, 'composition': composition})

p.model.add_subsystem('thermo', thermo, promotes=['T', 'P', 'composition'])

p.setup(force_alloc_complex=True)
p.run_model()

p

+  
+  ==========================
+  thermo.base_thermo.chem_eq
+  ==========================
+  NL: Newton 0 ; 0.185589463 1
+  NL: Newton 1 ; 0.625416649 3.36989309
+  NL: Newton 2 ; 1.77484595 9.56329052
+  NL: Newton 3 ; 0.101422604 0.546489024
+  NL: Newton 4 ; 1307.53537 7045.31038
+  NL: Newton 5 ; 0.00232776883 0.01254257
+  NL: Newton 6 ; 2.10435662e-08 1.13387721e-07
+  NL: Newton Converged
+  
+  ==========================
+  thermo.base_thermo.chem_eq
+  ==========================
+  NL: Newton 0 ; 3.36265871e-10 1
+  NL: Newton Converged
+  
+  ==========================
+  thermo.base_thermo.chem_eq
+  ==========================
+  NL: Newton 0 ; 1.04215364e-10 1
+  NL: Newton Converged
+  
+  ==========================
+  thermo.base_thermo.chem_eq
+  ==========================
+  NL: Newton 0 ; 5.87234717e-12 1
+  NL: Newton Converged


In [ ]:
1/ sum(p['thermo.base_thermo.n'])

np.float64(7.349013275026263)

In [ ]:
mole_species = p['thermo.base_thermo.n']

In [ ]:
mole_species

array([1.55920128e-09, 1.00000000e-10, 9.07151253e-02, 4.53575619e-02,
       1.00000000e-10, 1.00000000e-10, 1.00000000e-10, 1.00000000e-10])

In [ ]:
print(p.model.thermo.base_thermo.products)

AttributeError: 'SetTotalTP' object has no attribute 'products'

In [ ]:
print(p.model.thermo.base_thermo.thermo.products)

['H', 'HO2', 'H2', 'H2O', 'H2O2', 'O', 'OH', 'O2']


In [ ]:
n_sum = sum(p['thermo.base_thermo.n'])

In [ ]:
mole_species[0]/n_sum

np.float64(1.1458590879871963e-08)

In [ ]:
mole_species[3]/n_sum

np.float64(0.3333333248094561)

In [ ]:
mole_species[2]/n_sum

np.float64(0.666666660057446)